import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Configuration
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
# Updated to point to the new full file generated by analyze_book_association.py
INPUT_FILE = os.path.join(SCRIPT_DIR, "output", "frequent_itemsets.csv") 
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "visualizations")

# Colors
PRIMARY_COLOR = '#4F46E5' # Indigo
SECONDARY_COLOR = '#10B981' # Emerald
TERTIARY_COLOR = '#F59E0B' # Amber

def visualize_itemsets():
    if not os.path.exists(INPUT_FILE):
        print(f"File not found: {INPUT_FILE}")
        return

    # Load data
    df = pd.read_csv(INPUT_FILE)
    
    # Map Count to Frequency if necessary (to keep variable naming consistent)
    if 'Frequency' not in df.columns and 'Count' in df.columns:
        df['Frequency'] = df['Count']

    # Ensure visualizations directory exists
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    # Add Type column for coloring if not exists (frequent_itemsets.csv has Itemset_Size)
    if 'Type' not in df.columns and 'Itemset_Size' in df.columns:
        df['Type'] = df['Itemset_Size'].apply(lambda x: f"{x}-Itemset")

    # 1. Top 15 All Itemsets
    plt.figure(figsize=(12, 8))
    top_itemsets = df.sort_values(by='Frequency', ascending=False).head(15)
    
    sns.barplot(
        data=top_itemsets,
        y='Itemset',
        x='Frequency',
        hue='Type',
        palette={'1-Itemset': PRIMARY_COLOR, '2-Itemset': SECONDARY_COLOR, '3-Itemset': TERTIARY_COLOR}
    )
    
    plt.title('Top 15 Most Frequent Itemsets', fontsize=16)
    plt.xlabel('Frequency', fontsize=12)
    plt.ylabel('Itemset', fontsize=12)
    plt.tight_layout()
    
    output_path = os.path.join(OUTPUT_DIR, "top_itemsets_frequency.png")
    plt.savefig(output_path)
    print(f"Saved visualization to: {output_path}")
    plt.close()

    # 2. Top 10 1-Itemsets (Single Books)
    df_single = df[df['Itemset_Size'] == 1].head(10)
    if not df_single.empty:
        plt.figure(figsize=(10, 6))
        sns.barplot(
            data=df_single,
            y='Itemset',
            x='Frequency',
            color=PRIMARY_COLOR
        )
        plt.title('Top 10 Most Frequent 1-Itemsets (Single Books)', fontsize=14)
        plt.xlabel('Frequency')
        plt.ylabel('Book')
        plt.tight_layout()
        plt.savefig(os.path.join(OUTPUT_DIR, "top_1_itemsets.png"))
        plt.close()

    # 3. Top 10 2-Itemsets (Book Pairs)
    df_pairs = df[df['Itemset_Size'] == 2].head(10)
    if not df_pairs.empty:
        plt.figure(figsize=(10, 6))
        sns.barplot(
            data=df_pairs,
            y='Itemset',
            x='Frequency',
            color=SECONDARY_COLOR
        )
        plt.title('Top 10 Most Frequent 2-Itemsets (Book Pairs)', fontsize=14)
        plt.xlabel('Frequency')
        plt.ylabel('Book Pair')
        plt.tight_layout()
        plt.savefig(os.path.join(OUTPUT_DIR, "top_2_itemsets.png"))
        plt.close()

    # 4. Top 10 3-Itemsets (Book Triplets)
    df_triplets = df[df['Itemset_Size'] == 3].head(10)
    if not df_triplets.empty:
        plt.figure(figsize=(10, 6))
        sns.barplot(
            data=df_triplets,
            y='Itemset',
            x='Frequency',
            color=TERTIARY_COLOR
        )
        plt.title('Top 10 Most Frequent 3-Itemsets (Book Triplets)', fontsize=14)
        plt.xlabel('Frequency')
        plt.ylabel('Book Triplet')
        plt.tight_layout()
        plt.savefig(os.path.join(OUTPUT_DIR, "top_3_itemsets.png"))
        plt.close()
        print(f"Saved visualization for 3-itemsets")

if __name__ == "__main__":
    visualize_itemsets()
